events {}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://spline-web-ui:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /consumer/ {
            proxy_pass http://spline-rest-server:8080/consumer/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
